-- COPY OF CROSS CHANNEL ATTRIBUTION VIEW 
SELECT 
    PURCHASES.TIER_1
    -- , PURCHASES.TIER_2
    , PURCHASES.CONVERSIONS
    , PURCHASES.REVENUE
    , SPEND.SPEND
    , CASE 
        WHEN SPEND.SPEND > 0 THEN SPEND.SPEND / PURCHASES.CONVERSIONS
        ELSE 0
      END AS CPA
    , CASE
        WHEN SPEND.SPEND > 0 THEN PURCHASES.REVENUE / SPEND.SPEND
        ELSE 0
     END AS ROAS
FROM (
    SELECT 
        TIER_1
        -- , TIER_2
        , SUM(NORMALIZED) AS CONVERSIONS
        , SUM(REVENUE_NORMALIZED) AS REVENUE
    FROM ...
    WHERE DATE > '2023-11-4'
    GROUP BY TIER_1
    -- , TIER_2
    ORDER BY CONVERSIONS DESC
) PURCHASES
LEFT JOIN 
(
    SELECT
        TIER_1
        -- , TIER_2
        , SUM(SPEND) AS SPEND
    FROM ...
    WHERE DATE > '2023-11-04'
    GROUP BY TIER_1
    -- , TIER_2  
) SPEND
ON PURCHASES.TIER_1 = SPEND.TIER_1
-- AND PURCHASES.TIER_2 = SPEND.TIER_2
ORDER BY PURCHASES.CONVERSIONS DESC;
